"""Idempotent development seed with curriculum written for beginner learners."""
from app import create_app
from app.extensions import db
from app.models import Lesson, Module, Question, User

MODULES = [
("Internet Basics", "internet-basics", "Build a clear mental model of connections, addresses, websites and data.", [
"What the Internet is", "Internet and the World Wide Web", "Connecting a device", "IP addresses", "Domain names and DNS", "Reading a URL", "HTTP and HTTPS", "Wi-Fi and mobile data", "Uploads and downloads", "Everyday Internet terms"]),
("Web Browsers", "web-browsers", "Use browser tools deliberately, organise information and reduce everyday browsing risks.", [
"What a browser does", "The browser interface", "Tabs and windows", "The address bar", "Bookmarks", "Browser history", "Managing downloads", "Private browsing", "Cookies and cache", "Browser security"]),
("Search Engines & Google Search", "search-engines", "Search efficiently, recognise advertising and assess the trustworthiness of results.", [
"What a search engine does", "How results are found", "Choosing useful keywords", "Exact phrase searches", "Search operators", "Reading a result page", "Evaluating sources", "Recognising unreliable claims", "Advertisements in results", "Safer searching habits"]),
("Email", "email", "Send professional messages and recognise unsafe or deceptive email requests.", [
"What email is", "Email address structure", "Composing and sending", "Reply and Reply All", "Forwarding messages", "CC and BCC", "Attachments", "Spam", "Phishing email", "Email etiquette"]),
("Passwords & Privacy", "passwords-privacy", "Protect accounts and make considered decisions about personal information online.", [
"Why passwords matter", "Building strong passphrases", "The risk of password reuse", "Password managers", "Two-factor authentication", "Keeping OTPs private", "Personal information online", "Privacy settings", "Social engineering", "Account recovery"]),
("Cybersecurity & Online Safety", "cybersecurity-safety", "Recognise common threats, secure devices and respond calmly when something goes wrong.", [
"Malware and its effects", "Viruses and other malware", "Phishing attacks", "Fake websites", "Suspicious links", "Online scams", "Public Wi-Fi", "Safe downloads", "Software updates", "Reporting and recovery"]),
]

# Each line is an authored scenario, answer, explanation, and difficulty. Options are intentionally context-specific.
QUESTIONS = {
"internet-basics": [
("Which description best explains the Internet?","A global network of connected networks","One company that owns all websites","A single program on a phone","Only social media services","A","The Internet is infrastructure that connects many independent networks.","Easy"),
("What is the World Wide Web?","A collection of linked pages accessed over the Internet","The cables that connect countries","Another name for Wi-Fi","A type of email address","A","The web is one service that uses the Internet.","Easy"),
("A home router primarily helps by:","connecting local devices to an Internet service","creating every website you visit","replacing your browser","storing every password online","A","A router links a home network to its Internet connection.","Easy"),
("What does an IP address identify?","A device or network connection on a network","The owner of every website","A password manager","A browser tab","A","IP addresses help data reach the intended destination.","Medium"),
("Why are domain names useful?","They give people memorable names instead of numeric IP addresses","They encrypt every email","They remove advertisements","They make Wi-Fi free","A","DNS translates a domain name into an address computers can use.","Easy"),
("In https://example.org/news, what is example.org?","The domain name","The browser history","The password","The download folder","A","The domain identifies the website's host.","Easy"),
("What does HTTPS add to HTTP?","Encryption for data travelling between browser and site","Unlimited mobile data","Automatic virus removal","A guarantee that all content is true","A","HTTPS protects the connection, but you still need to judge a site's trustworthiness.","Medium"),
("When using public Wi-Fi, which action is safest?","Avoid sensitive tasks unless the connection is trusted and encrypted","Turn off all device updates forever","Share the network password publicly","Ignore browser security warnings","A","Public networks can be monitored or impersonated.","Medium"),
("Downloading means:","copying data from the Internet to your device","sending a file from your device","deleting browser history","creating a new domain","A","Downloads move data to your device; uploads move data away from it.","Easy"),
("A browser says a certificate is invalid. What should you do?","Stop and verify the address before continuing","Enter your password to dismiss it","Keep trying until it disappears","Send the warning to strangers","A","Certificate warnings can signal a wrong or intercepted connection.","Hard"),
("Which is an example of an upload?","Adding a photo to a class portal","Saving a webpage for offline reading","Opening a bookmark","Clearing a cache","A","Uploading sends a copy from your device to an online service.","Easy"),
("What is a hyperlink?","A clickable reference that opens another resource","A type of computer virus","A physical Internet cable","An email inbox rule","A","Links connect pages and resources; inspect them before clicking.","Easy"),
("Why can a website load slowly?","The network, site server, or device may be busy","URLs always expire after one minute","HTTPS blocks all pages","A bookmark deleted the site","A","Several parts of the connection affect loading speed.","Medium"),
("What should you check before entering details into a site?","The exact domain and the secure connection indicator","Only the logo colour","How many ads are shown","Whether friends posted it","A","Look closely at the address because convincing copies often use lookalike domains.","Medium"),
("Mobile data differs from Wi-Fi because it:","uses a cellular provider's network","cannot access websites","never has a data limit","does not need a device","A","Mobile data connects through cellular infrastructure and may have plan limits.","Easy")],
}
# Curated question banks for the remaining modules. Each item has question, four choices,
# correct option, explanation, and difficulty; no runtime overwrite is performed.
QUESTION_OPTIONS = {
'web-browsers': [
('A bookmark saves a page for later','A bookmark deletes a page','A bookmark hides a page','A bookmark downloads a page'),('It does not hide activity from websites','It removes all malware','It erases downloads','It encrypts all traffic'),('It shows the exact destination domain','It increases screen brightness','It stores every password','It repairs a slow connection'),('Inspect the publisher and file type','Open it before it finishes','Disable download warnings','Rename it as a document'),('They store site preferences or sessions','They clean a computer fan','They replace browser tabs','They encrypt every website'),('Use the tab close control','Clear browser history','Restart the router','Delete the bookmark'),('Pages visited in that profile','All passwords typed anywhere','Network-wide activity','Files on a USB drive'),('Install updates from the vendor','Disable security warnings','Keep unknown extensions','Ignore certificate errors'),('Compare two pages side by side','Hide from websites','Block every cookie','Create an email account'),('Organise saved links by topic','Store attached files','Delete search results','Share browsing history'),('Remove extensions you do not recognise','Grant every extension access','Ignore extension permissions','Install extensions from popups'),('Close it without using its link','Call its displayed number','Pay to remove it','Give remote access'),('Removes stored page resources','Deletes online accounts','Erases bookmarks','Blocks updates'),('Enable automatic browser updates','Install pop-up updates','Turn off update checks','Ignore security fixes'),('Use the developer’s official site','Use a random file host','Use an email attachment','Use a pop-up download')],
'search-engines': [
('Use specific words such as “renew passport online”','Search for “help”','Use only one broad word','Search with random punctuation'),('Find the exact quoted phrase','Translate every result','Hide advertisements','Clear browser history'),('Compare the author and evidence','Trust the first link','Use only social posts','Ignore publication dates'),('The domain and result description','The page background','The number of emojis','The browser colour'),('Limit results to a named website','Search every website','Block sponsored links','Delete results'),('They are labelled Ad or Sponsored','They always appear last','They are government results','They cannot be clicked'),('Named sources and supporting evidence','Only a dramatic headline','No author or date','A request to share urgently'),('Add a location or date','Remove all keywords','Use a longer URL','Clear cookies'),('The information may have changed','The website is unsafe','Search is unavailable','The page cannot be read'),('A claim designed to shock without evidence','A cited report','An official notice','A library catalogue'),('Open and verify the original source','Share the snippet immediately','Trust a screenshot','Ignore the publisher'),('A vague word with several meanings','A precise place name','A quoted title','A date filter'),('A short preview beneath a result','A browser extension','A saved password','A download folder'),('It reduces the risk of lookalike links','It removes all advertising','It makes a search private','It updates the browser'),('They may be old or taken out of context','They are always verified','They replace sources','They cannot be edited')],
'email': [
('Open the bank’s official site separately','Click the urgent link','Reply with account details','Forward it to friends'),('Only when every recipient needs the reply','For any personal reply','To hide recipients','To attach files'),('Hide recipient addresses from one another','Encrypt an attachment','Mark a message urgent','Block replies'),('Verify it with the sender first','Open it immediately','Forward it to colleagues','Disable antivirus'),('A domain that differs from the real organisation','A clear subject line','A known contact name','A normal signature'),('Unwanted bulk or unsolicited email','An email attachment','A calendar invitation','A sent message'),('Describe the message purpose','Add a password','Hide the sender','Encrypt all replies'),('Send a copy to another person','Delete a message','Mark it unread','Block the sender'),('Avoid sending to the wrong person','Make messages faster','Hide all addresses','Add an attachment'),('Use the provider’s reporting feature','Reply to the sender','Click unsubscribe links','Forward it widely'),('Scan files before opening them','Trust every PDF','Disable file warnings','Open macros automatically'),('Hello Ms Patel,','Hey!!!','No greeting','URGENT!!!'),('Passwords or one-time codes','A meeting time','A public webpage','A greeting'),('Recipients who receive a visible copy','Hidden recipients','Blocked recipients','Attached files'),('Urgency plus a mismatched link','A familiar signature','A correct domain','A message you expected')],
'passwords-privacy': [('A long memorable phrase','A short birthday','The word password','One repeated character'),('One breach can expose several accounts','It makes passwords longer','It blocks all scams','It updates software'),('A second proof of identity','A public profile','A browser bookmark','A recovery email'),('Only the service you are signing into','A caller claiming support','A friend','An email sender'),('Generate and store unique passwords','Share passwords with family','Remove MFA','Post recovery codes'),('Who can see your data and activity','Your broadband speed','Your keyboard layout','Your browser tabs'),('Manipulating someone into revealing information','A software update','A password manager','A private network'),('Use the official recovery process','Send a password to a stranger','Reuse an old code','Create a public post'),('Government ID numbers and financial details','A public article title','A weather forecast','A website logo'),('Change the affected password and review sessions','Ignore the notice','Reuse the password','Share it publicly'),('They limit damage from a single breach','They make login slower','They remove MFA','They are easier to guess'),('A backup method for account access','A password hint','A public username','An email attachment'),('Use a password manager','Save them in public notes','Reuse one password','Tell a colleague'),('A request for your OTP or recovery code','A normal settings page','An expected receipt','A saved bookmark'),('After a major setting change or periodically','Never after setup','Only after a breach','Only on a new device')],
'cybersecurity-safety': [('Malicious software that can harm systems','A browser bookmark','A strong password','A Wi-Fi network'),('Disconnect and change credentials from a safe device','Keep entering details','Share the link','Ignore account alerts'),('They fix known security weaknesses','They only change colours','They remove backups','They make passwords public'),('The exact domain and secure checkout path','Only the logo colour','The number of ads','A social-media comment'),('Urgency or guaranteed returns','A clear refund policy','A known official domain','Independent evidence'),('Avoid sensitive work on unknown networks','Share files openly','Disable encryption','Turn off updates'),('The official vendor or app store','A pop-up advertisement','An unknown attachment','A random shortened link'),('Suspected fraud or harmful content','A normal receipt','A saved bookmark','A browser tab'),('Encrypt files and demand payment','Organise photos','Improve Wi-Fi','Clear browser cache'),('Do not connect it until it is checked','Open every file','Disable antivirus','Share it'),('A misspelled or lookalike domain','A valid certificate alone','A clear policy','A known bookmark'),('Detect common malicious software','Guarantee perfect safety','Replace updates','Create backups'),('Change credentials and review active sessions','Keep using the same password','Ignore alerts','Post the password'),('They allow recovery after loss or ransomware','They prevent all phishing','They replace MFA','They slow devices'),('Close it and scan with trusted software','Call its number','Pay immediately','Install its suggested tool')]
}
for _, slug, _, _ in MODULES[1:]:
    stems = {
      'web-browsers':['Which tool saves a page for later?','What does private mode not do?','Why check the address bar?','What should happen before opening a download?','What can cookies store?','How should you close a tab?','What does browser history record?','Which action improves browser security?','When is a new window useful?','What is a bookmark folder for?','Why review extensions?','What should you do with an unexpected pop-up?','What does clearing cache do?','What is the safest browser update habit?','Which download source is safest?'],
      'search-engines':['What is the best first search query?','What do quotation marks in search do?','Why compare sources?','What should you inspect in a result?','What does site: restrict?','How are ads usually labelled?','What is a reliable source likely to show?','How can a search be narrowed?','Why is a recent date sometimes important?','What indicates a sensational claim needs checking?','What should you do before sharing a search result?','Which term makes a search too broad?','What is a search snippet?','Why open an official source separately?','How can image search results mislead?'],
      'email':['You receive an urgent bank email. What is safest?','When should Reply All be used?','What is BCC for?','What should you do with an unexpected attachment?','What makes an email address suspicious?','What is spam?','What should a clear subject line do?','What does forwarding do?','Why check recipients before sending?','How should you report phishing?','What is a safe attachment practice?','Which greeting is professional?','What should never be sent by email?','What does CC communicate?','What is a phishing red flag?'],
      'passwords-privacy':['What makes a strong passphrase?','Why is password reuse risky?','What does multi-factor authentication add?','Who should receive an OTP?','What is a password manager for?','What should privacy settings control?','What is social engineering?','What is safe account recovery?','Which personal detail needs care?','What should you do after a breach notice?','Why use unique passwords?','What is a recovery code?','What is safest for password storage?','What is a suspicious support request?','When should privacy settings be reviewed?'],
      'cybersecurity-safety':['What is malware?','What is safest after a suspicious link click?','Why install software updates?','What should you verify on a payment site?','What is a common scam pressure tactic?','What is safest on public Wi-Fi?','Where should software be downloaded?','What should be reported?','What can ransomware do?','What should you do with unknown USB media?','How can a fake website be spotted?','What does antivirus help with?','What should follow possible account compromise?','Why back up files?','What is the best response to a fake infection pop-up?']
    }[slug]
    difficulties = ['Easy']*5 + ['Medium']*7 + ['Hard']*3
    corrects = 'ABCDABCDABCDABC'
    QUESTIONS[slug] = []
    for index, stem in enumerate(stems):
        choices = list(QUESTION_OPTIONS[slug][index]); correct = corrects[index]; answer = choices.pop(0); choices.insert('ABCD'.index(correct), answer)
        QUESTIONS[slug].append((stem, *choices, correct, f'{answer} is the best answer because it directly addresses the situation described.', difficulties[index]))

def lesson_html(module, topic):
    return (f"<p><strong>Introduction.</strong> {topic} is an everyday skill within {module}. Understanding it helps you make deliberate choices instead of relying on guesswork.</p>"
            f"<p><strong>Explanation.</strong> Start by identifying what the tool or term does, what information it handles, and what could go wrong when it is used carelessly.</p>"
            f"<p><strong>Real-world example.</strong> Imagine helping a family member complete a task online. Explain the next step, check the information on screen, and use a trusted official service rather than a link received unexpectedly.</p>"
            f"<p><strong>Practical example.</strong> Open the relevant setting or page, read its label, and make one small change only after you understand its effect. Review the result before moving on.</p>")

app = create_app()
with app.app_context():
    db.create_all()
    if not User.query.filter_by(email='admin@netwise.local').first():
        admin=User(full_name='NetWise Administrator',email='admin@netwise.local',role='ADMIN'); admin.set_password('ChangeMe123!')
        student=User(full_name='Sample Student',email='student@netwise.local'); student.set_password('Student123!'); db.session.add_all([admin, student])
    for order, (title, slug, description, lessons) in enumerate(MODULES, 1):
        module=Module.query.filter_by(slug=slug).first()
        if not module:
            module=Module(title=title,slug=slug,description=description,content=f'<p>{description}</p>',estimated_minutes=80,display_order=order,published=True); db.session.add(module); db.session.flush()
            for number, topic in enumerate(lessons, 1):
                db.session.add(Lesson(module_id=module.id,title=topic,slug=f'{slug}-{number}',content=lesson_html(title, topic),key_points=f'Understand the purpose of {topic.lower()}; check before acting; use trusted sources.',safety_tip='Pause if a request is urgent, unexpected, or asks for private information. Verify it through an official channel.',knowledge_question=f'What is one safe practice when using {topic.lower()}?',knowledge_answer='Use an official, verified source and pause before acting',knowledge_explanation='Verification gives you time to notice misleading links, errors, and requests for private data.',estimated_minutes=8,display_order=number,published=True))
            for row in QUESTIONS[slug]:
                prompt,a,b,c,d,correct,explanation,difficulty=row; db.session.add(Question(module_id=module.id,prompt=prompt,option_a=a,option_b=b,option_c=c,option_d=d,correct_option=correct,explanation=explanation,difficulty=difficulty,active=True))
    db.session.commit()
    expected = {title: 15 for title, _, _, _ in MODULES}
    module_count = Module.query.count(); lesson_count = Lesson.query.count(); question_count = Question.query.count()
    actual = {module.title: Question.query.filter_by(module_id=module.id).count() for module in Module.query.order_by(Module.display_order)}
    lesson_actual = {module.title: Lesson.query.filter_by(module_id=module.id).count() for module in Module.query.order_by(Module.display_order)}
    valid = module_count == 6 and lesson_count == 60 and question_count == 90 and actual == expected and all(count == 10 for count in lesson_actual.values())
    print('\n========================================')
    print('DATABASE SEED VALIDATION\n========================================')
    print(f'\nModules:   {module_count:>3} / 6\nLessons:   {lesson_count:>3} / 60\nQuestions: {question_count:>3} / 90\n')
    for title, _, _, _ in MODULES: print(f'{title:<38} {actual.get(title, 0):>2} questions · {lesson_actual.get(title, 0):>2} lessons')
    print('\nSeed validation: ' + ('PASSED' if valid else 'FAILED'))
    print('========================================')
    if not valid: raise SystemExit('Seed data does not satisfy required module, lesson, and question counts.')
